services:
  cache:
    image: redis:7
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:14.13
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=inveniordm"
      - "POSTGRES_PASSWORD=inveniordm"
      - "POSTGRES_DB=inveniordm"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mq:
    image: rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  search:
    image: opensearchproject/opensearch:2
    restart: "unless-stopped"
    volumes:
      - os_data:/usr/share/opensearch/data 
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9600:9600"

  frontend:
    image: ghcr.io/sharedrdm/inveniordm-mug:main-nginx
    # # uncomment if want to build localy.
    # build:
    #   context: .
    #   dockerfile: Dockerfile-nginx-mug
    restart: "unless-stopped"
    pull_policy: always
    depends_on:
      - web-ui
      - web-api
    ports:
      - "8000:8000"
    volumes:
      - static_data:/opt/invenio/var/instance/static

  web-ui:
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini"]
    pull_policy: always
    image: ghcr.io/sharedrdm/instance:v0.0.1-mug
    restart: "unless-stopped"
    env_file: .env.temp
    depends_on:
      - search
      - cache
      - mq
    volumes:
      - static_data:/opt/invenio/var/instance/static
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    # ports:
    #   - "5000:5000"

  web-api:
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_rest.ini"]
    pull_policy: always
    restart: "unless-stopped"
    image: ghcr.io/sharedrdm/instance:v0.0.1-mug
    env_file: .env.temp
    depends_on:
      - search
      - cache
      - mq
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    # ports:
    #   - "5000:5000"

  worker:
    command: ["celery -A invenio_app.celery worker --beat --events --loglevel=INFO"]
    image: ghcr.io/sharedrdm/instance:v0.0.1-mug
    restart: "unless-stopped"
    pull_policy: always
    env_file: .env.temp
    depends_on:
      - search
      - cache
      - mq
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data

volumes:
  redis_data: 
  postgres_data:
  rabbitmq_data:
  static_data: 
  uploaded_data:
  os_data:
  archived_data:
